version: '3'

volumes:
  pg_data:
  static_volume:
  media_volume:
  data_volume:
  logs_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static/
      - media_volume:/media/
      - data_volume:/data/
      - logs_volume:/logs/
    ports:
      - 8012:80
  nginx:
    build: ./infra/
    env_file: .env
    ports:
      - 8021:80
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media/
  bot:
    build: ./bot/
    env_file: .env
    restart: always
    volumes:
      - logs_volume:/logs/
      - media_volume:/media/