# Generated by Django 5.0.3 on 2024-03-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_item_description_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, null=True, verbose_name="password"),
        ),
    ]
