# Generated by Django 5.0.3 on 2024-03-27 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_cartitem_shoppingcart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="shopping_cart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.shoppingcart",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="shoppingcart",
            name="items",
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="items",
            field=models.ManyToManyField(through="shop.CartItem", to="shop.item"),
        ),
    ]
