# Generated by Django 5.0.3 on 2024-03-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_cartitem_shopping_cart_remove_shoppingcart_items_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "Корзина/Товар",
                "verbose_name_plural": "Корзины/Товары",
            },
        ),
        migrations.AlterModelOptions(
            name="shoppingcart",
            options={"verbose_name": "Корзина", "verbose_name_plural": "Корзины"},
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="order_time",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("item", "shopping_cart"), name="unique_item_shopping_cart"
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("user", "order_time"), name="unique_user_order_time"
            ),
        ),
    ]
