# Generated by Django 5.0.3 on 2024-03-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_alter_cartitem_options_alter_shoppingcart_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="order_time",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
