# Generated by Django 5.0.3 on 2024-03-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_shoppingcart_order_time"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="shoppingcart",
            name="unique_user_order_time",
        ),
    ]
