# Generated by Django 5.0.3 on 2024-03-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0015_remove_shoppingcart_unique_user_order_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcart",
            name="order_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("user", "order_time"), name="unique_user_order_time"
            ),
        ),
    ]
