# Generated by Django 5.0.3 on 2024-03-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0016_alter_shoppingcart_order_time_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
