# Generated by Django 5.0.3 on 2024-03-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_delete_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingcart",
            name="address",
            field=models.CharField(blank=True, null=True),
        ),
    ]
