# Generated by Django 5.0.3 on 2024-03-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_shoppingcart_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
