# Generated by Django 5.0.3 on 2024-03-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_item_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
